import os
import anthropic
import re
from datetime import date

def update_dashboard(dispatch_text, legal_rows):
    """Bypasses HTML logic and injects directly into anchor comments"""
    try:
        with open("index.html", "r") as f:
            html = f.read()

        # Update Main Dispatch Box
        dispatch_regex = r".*?"
        new_dispatch = f"\n<p class='text-slate-300'>{dispatch_text}</p>\n"
        html = re.sub(dispatch_regex, new_dispatch, html, flags=re.DOTALL)

        # Update Litigation Feed
        feed_regex = r".*?"
        new_feed = f"\n{legal_rows}\n"
        html = re.sub(feed_regex, new_feed, html, flags=re.DOTALL)

        with open("index.html", "w") as f:
            f.write(html)
        print("🖥️ Dashboard successfully injected via Anchor Markers.")
    except Exception as e:
        print(f"⚠️ Injection failed: {e}")

def run_sovereign_dispatcher():
    # 1. Grab raw telemetry from your scouts
    # In a real run, this reads the files generated by your other scripts
    raw_legal = "FCX: 2:24-cv-00123 (AZ); RIO: Environmental Review (WA); BHP: Labor Update."
    
    # 2. Attempt AI Analysis (The Brain)
    try:
        client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=1000,
            system="Summarize ZSP v2.1 Convergence findings concisely.",
            messages=[{"role": "user", "content": f"Analyze: {raw_legal}"}]
        )
        final_dispatch = message.content[0].text
    except Exception as e:
        # FAIL-SAFE: Use raw signals if credits are low
        print(f"🛑 AI Analytics Paused: {e}")
        final_dispatch = f"AI ANALYSIS PENDING. RAW TELEMETRY: {raw_legal}"

    # 3. Format the Side Feed Rows
    legal_html_rows = ""
    for entry in raw_legal.split(';'):
        legal_html_rows += f"""
        <div class="legal-row">
            <p class="text-blue-400 font-bold font-mono uppercase text-[9px]">SIGNAL DETECTED</p>
            <p class="text-slate-300 mt-1">{entry.strip()}</p>
        </div>"""

    # 4. Push to Dashboard
    update_dashboard(final_dispatch, legal_html_rows)

if __name__ == "__main__":
    run_sovereign_dispatcher()
