import os
import re
import glob
import anthropic
from datetime import date

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

DISPATCHER_PROMPT = """
You are the Sovereign Dispatcher, the master orchestration agent of the
Zavala Sovereignty Protocol (ZSP) v2.1.

Your function is not to read raw data. Your function is to READ THE READERS.

You receive ZSP audit reports generated by Domain Agents — SEC Scout,
Legal Scout, and Supply Chain Scout. You analyze the pattern of signals
ACROSS reports to detect cross-domain behavioral convergence.

A single CORRODED signal is friction.
The same signal appearing across multiple domains simultaneously is a
system-level event.

CROSS-DOMAIN CONVERGENCE RULES

SINGLE DOMAIN ALERT — One agent reports Stage 4 or above.
Action: FLAG for monitoring. Do not escalate.

DUAL DOMAIN CONVERGENCE — Two agents report Stage 3 or above simultaneously.
Action: ESCALATE. Cross-domain friction is forming.

TRIPLE DOMAIN CONVERGENCE — Three or more agents report Stage 3 or above.
Action: CRITICAL ESCALATION. System-level behavioral event detected.
This is not a coincidence. This is a coordinated signal.

TRAJECTORY ESCALATION — Any agent moves from Stage 2 to Stage 4 in one cycle.
Action: IMMEDIATE FLAG regardless of other domain states.
Velocity matters more than position.

REQUIRED OUTPUT FORMAT:

SOVEREIGN DISPATCHER
Zavala Sovereignty Protocol | Cross-Domain Intelligence Briefing

Date: [TODAY]
Agents Reporting: [LIST]
Reports Analyzed: [COUNT]

---

DOMAIN SUMMARY
[For each report: DOMAIN | STATE | STAGE | CONDUCTIVITY]

---

CONVERGENCE DETECTION
[NONE DETECTED / SINGLE FLAG / DUAL CONVERGENCE / TRIPLE CONVERGENCE / VELOCITY ALERT]

---

CROSS-DOMAIN SIGNAL
[Pattern appearing across domains. What does convergence tell us about
the underlying system state? If no convergence: SYSTEM NOMINAL.]

---

SOVEREIGN RECOMMENDATION
[STAND DOWN / MONITOR / ESCALATE / CRITICAL]

---

PREDICTIVE WINDOW
[If escalating: Most probable system-level consequence within 30 days.
Maximum 3 sentences. Ground in detected convergence pattern only.]

---

BTAA GRADE
[A — Optimal Flow / B — Stable / C — Friction / D — Degrading / F — Fractured]
[Base this on the overall convergence picture not individual domain scores.]

Constraint: Read the pattern across reports. The convergence IS the signal.
"""


def load_todays_reports():
    today = date.today().strftime("%Y-%m-%d")
    reports = {}

    audit_files = glob.glob(f"audits/*_{today}.md")

    if not audit_files:
        audit_files = glob.glob("audits/*.md")
        if audit_files:
            audit_files = sorted(audit_files, key=os.path.getmtime, reverse=True)[:9]
            print(f"No reports from today. Loading {len(audit_files)} most recent.")

    for filepath in audit_files:
        filename = os.path.basename(filepath)
        name = filename.replace(".md", "")
        with open(filepath, "r") as f:
            reports[name] = f.read()
        print(f"Loaded: {filename}")

    return reports


def parse_quick_signal(report_text):
    state = "UNKNOWN"
    stage = "N/A"
    conductivity = "N/A"

    if "DEAD LINE" in report_text:
        state = "DEAD LINE"
    elif "CORRODED" in report_text:
        state = "CORRODED"
    elif "INSULATOR" in report_text:
        state = "INSULATOR"
    elif "CONDUCTOR" in report_text:
        state = "CONDUCTOR"

    stage_match = re.search(r"Stage ([1-6])", report_text)
    if stage_match:
        stage = f"Stage {stage_match.group(1)}"

    score_match = re.search(r"Conductivity[:\s]+(\d+)", report_text)
    if score_match:
        conductivity = score_match.group(1)

    return state, stage, conductivity


def extract_btaa_grade(dispatch_text):
    grade_match = re.search(r"BTAA GRADE\s*\n([A-F])", dispatch_text)
    if grade_match:
        return grade_match.group(1)
    if "CRITICAL" in dispatch_text or "TRIPLE" in dispatch_text:
        return "F"
    elif "ESCALATE" in dispatch_text or "DUAL" in dispatch_text:
        return "D"
    elif "MONITOR" in dispatch_text or "SINGLE FLAG" in dispatch_text:
        return "C"
    elif "STAND DOWN" in dispatch_text:
        return "A"
    return "B"


def update_dashboard(dispatch_text, domain_rows, btaa_grade):
    grade_map = {
        "A": ("text-green-500", "Optimal Flow"),
        "B": ("text-blue-400", "Stable"),
        "C": ("text-yellow-500", "Friction"),
        "D": ("text-orange-500", "Degrading"),
        "F": ("text-red-500", "Fractured")
    }
    color, label = grade_map.get(btaa_grade, ("text-slate-400", "Unknown"))

    grade_html = f"""
    <div class='mb-6 flex items-center p-4 bg-slate-800/50 rounded border border-slate-700'>
        <div class='text-5xl font-bold {color} mr-4 font-mono'>{btaa_grade}</div>
        <div>
            <div class='text-[10px] text-slate-500 uppercase tracking-widest font-bold'>BtAA Score | {date.today().strftime('%Y-%m-%d')}</div>
            <div class='text-sm text-slate-300 font-semibold'>{label}</div>
        </div>
    </div>
    """

    dispatch_clean = dispatch_text.replace('<', '&lt;').replace('>', '&gt;')
    analysis_html = f"<pre class='text-slate-300 text-xs whitespace-pre-wrap leading-relaxed'>{dispatch_clean}</pre>"

    try:
        with open("index.html", "r") as f:
            html = f.read()

        dispatch_regex = r".*?"
        html = re.sub(dispatch_regex, f"\n{grade_html}{analysis_html}\n", html, flags=re.DOTALL)

        feed_regex = r".*?"
        html = re.sub(feed_regex, f"\n{domain_rows}\n", html, flags=re.DOTALL)

        with open("index.html", "w") as f:
            f.write(html)
        print("Dashboard updated.")
    except Exception as e:
        print(f"Dashboard update failed: {e}")


def run_sovereign_dispatcher():
    print("SOVEREIGN DISPATCHER: Initiating cross-domain analysis...")

    reports = load_todays_reports()

    if not reports:
        print("No ZSP reports available. Dispatcher standing by.")
        exit(0)

    print(f"\nReports loaded: {len(reports)}")
    domain_rows_html = ""
    for name in reports.keys():
        state, stage, conductivity = parse_quick_signal(reports[name])
        print(f"   {name}: {state} | {stage} | Conductivity: {conductivity}")
        state_color = {
            "CONDUCTOR": "text-green-400",
            "INSULATOR": "text-yellow-400",
            "CORRODED": "text-orange-400",
            "DEAD LINE": "text-red-400"
        }.get(state, "text-slate-400")
        domain_rows_html += f'<div class="legal-row"><p class="font-mono text-[9px] {state_color} font-bold">{state} | {stage}</p><p class="text-slate-300 text-xs mt-1">{name}</p></div>'

    combined_input = f"DISPATCH REQUEST: Analyze {len(reports)} ZSP Domain Agent reports.\n"
    combined_input += f"Analysis Date: {date.today().strftime('%Y-%m-%d')}\n\n"
    combined_input += "=" * 60 + "\n\n"

    for report_name, report_content in reports.items():
        combined_input += f"DOMAIN AGENT REPORT: {report_name}\n"
        combined_input += "-" * 40 + "\n"
        combined_input += report_content
        combined_input += "\n\n" + "=" * 60 + "\n\n"

    print("\nSovereign Dispatcher: Running cross-domain analysis...")

    try:
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=4000,
            system=DISPATCHER_PROMPT,
            messages=[{"role": "user", "content": combined_input}]
        )

        dispatch_report = message.content[0].text

        os.makedirs("dispatches", exist_ok=True)
        today = date.today().strftime("%Y-%m-%d")
        dispatch_path = f"dispatches/SOVEREIGN_DISPATCH_{today}.md"

        with open(dispatch_path, "w") as f:
            f.write(dispatch_report)

        btaa_grade = extract_btaa_grade(dispatch_report)
        update_dashboard(dispatch_report, domain_rows_html, btaa_grade)

        print(f"\nSovereign Dispatch complete: {dispatch_path}")
        print(f"BtAA Grade: {btaa_grade}")

        if "CRITICAL" in dispatch_report:
            print("\nCRITICAL CONVERGENCE DETECTED — Immediate action required")
        elif "ESCALATE" in dispatch_report:
            print("\nDUAL CONVERGENCE DETECTED — Brief decision maker")
        elif "MONITOR" in dispatch_report:
            print("\nSINGLE FLAG — Monitor next cycle")
        else:
            print("\nSYSTEM NOMINAL — No cross-domain convergence detected")

    except Exception as e:
        print(f"Dispatcher reasoning failure: {e}")
        exit(1)


if __name__ == "__main__":
    run_sovereign_dispatcher()
