import os
import anthropic
import re
from datetime import date

def update_dashboard(dispatch_text, legal_rows):
    """The 'Injection' engine: Writes data directly into index.html"""
    try:
        with open("index.html", "r") as f:
            html = f.read()

        # 1. Update the Main Dispatch Box
        dispatch_pattern = r'<p class="text-slate-400 italic">.*?</p>'
        new_dispatch = f'<p class="text-slate-300">{dispatch_text}</p>'
        html = re.sub(dispatch_pattern, new_dispatch, html, flags=re.DOTALL)

        # 2. Update the Litigation Feed
        feed_pattern = r'.*?<div class="text-\[11px\] space-y-2">.*?</div>'
        new_feed = '<div class="text-[11px] space-y-2">' + legal_rows + '</div>'
        # We target the specific div inside the side feed
        html = re.sub(r'<div class="text-\[11px\] space-y-2">.*?</div>', new_feed, html, flags=re.DOTALL)

        with open("index.html", "w") as f:
            f.write(html)
        print("🖥️ Dashboard successfully updated with fresh telemetry.")
    except Exception as e:
        print(f"⚠️ Dashboard Injection Failed: {e}")

def run_sovereign_dispatcher():
    # 1. Gather raw data from your scouts
    # In a real run, these files are generated by docket_scout and supply_chain_scout
    raw_legal = "FCX: 2:24-cv-00123 (AZ); RIO: Environmental Review (WA); BHP: Labor Update."
    
    # 2. Attempt the "Brain" (Claude)
    try:
        client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        message = client.messages.create(
            model="claude-3-5-sonnet-20241022",
            max_tokens=1000,
            system="Summarize the ZSP v2.1 Convergence findings.",
            messages=[{"role": "user", "content": f"Analyze: {raw_legal}"}]
        )
        final_dispatch = message.content[0].text
    except Exception as e:
        # FAIL-SAFE MODE: If credits are low, use the raw data instead
        print(f"🛑 AI Analytics Paused: {e}")
        final_dispatch = f"ANALYSIS PENDING (Credit Reset Required). RAW SIGNAL: {raw_legal}"

    # 3. Format the Litigation Feed Rows
    # We create a nice HTML block for the side-bar
    legal_html_rows = ""
    for entry in raw_legal.split(';'):
        legal_html_rows += f"""
        <div class="legal-row">
            <p class="text-blue-400 font-bold font-mono uppercase tracking-tighter">SIGNAL DETECTED</p>
            <p class="text-slate-300 mt-1 text-[10px]">{entry.strip()}</p>
        </div>"""

    # 4. Push to Dashboard
    update_dashboard(final_dispatch, legal_html_rows)

if __name__ == "__main__":
    run_sovereign_dispatcher()
